### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by iisGmoney** [deepjyoti30/startpage#22]
This is less of an issue and more of a suggestion, it would be nice to add a settings page, so that you can have settings accessible in a way where anyone who doesn’t know how to edit the .json file can mess with the settings without breaking it

**Comment by deepjyoti30** [comment]
@iisGmoney Thanks for the suggestion, this is what I had in mind from the beginning but then I did updated the README for a while suggesting it's a headache building a GUI setting page, especially for those squares.

For a while I thought I will not add any settings page at all but then I thought adding a json editor would be a nice hack since without a settings page I can't push the extension to web stores and so I added that json editor. I will still consider your suggestion though but seriously, it's a real mess for me designing that atm.

**Comment by reesericci** [comment]
I think a JSON editor is fine and all the options are well-documented, as well as allowing @deepjyoti30 to work on new and improved features.

**Comment by reesericci** [comment]
@iisGmoney close?
@deepjyoti30 wontfix label

**Comment by reesericci** [comment]
@deepjyoti30 just filed a PR making some improvements to settings #29
