### ISSUE TITLE
AMO Link Broken

### ISSUE THREAD

**Issue by reesericci** [deepjyoti30/startpage#24]
The link to AMO for the extension is broken. (README)

**Comment by deepjyoti30** [comment]
@reesericci Yup, I'm aware of that. The extension was removed by the Firefox team because of a bit of code.

The code was that I was updating a div with ```innerHTML``` which is not safe and I understand that.

I did think I would reupload after changing the ```innerHtml``` part to ```innerText``` but then recently I added support to add colors from the config where I had to use something similar in order to chnage the color.

I did try to go for alternatives but it was unavoidable and so I think I won't be able to upload it to AMO anymore since it will end up getting rejected anyway.

The commit is https://github.com/deepjyoti30/startpage/commit/4b521b5a603219eaf622e77d19dec42bc9feb6cc in case you wanna check the source.

**Comment by reesericci** [comment]
That's a bummer, I know jQuery can change the css.

Reese Armstrong
"The best at everything, ever."
reesericci@nyctech.cloud (https://link.getmailspring.com/link/39FB7C73-AB8A-4D36-85C4-6AEAEEFFD946@getmailspring.com/0?redirect=mailto%3Areesericci%40nyctech.cloud&recipient=cmVwbHkrQUVWT1BEV01WRURFT0pTVExGWlZMQ040NkRaUkJFVkJOSEhDTUNOVEpFQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by reesericci** [comment]
#25 Filed a PR to remove the link from the README

**Comment by reesericci** [comment]
Merged, closed for now
