### ISSUE TITLE
Flicker on new tab open in Chrome

### ISSUE THREAD

**Issue by mkrasnitski** [deepjyoti30/startpage#33]
I have the message and weather disabled. However when I open a new tab I get consistent flickering of the default message every time. Here's an example of it: https://streamable.com/cvv731

Thanks

**Comment by deepjyoti30** [comment]
@mkrasnitski You are using i3?? And what is the compositor you're using?

I have actually personally faced this issue and I think it is because one of `i3` or `compton`. That's because I faced this flickering on other sites as well. It happens sometimes, not all the time. One example is slides.google.com, it was just unusable at one point for me.

Also this happened to me on Chrome.

All, in all, I really think the issue is not of the extension and instead is caused by `Chrome + compton/i3`.

**Comment by reesericci** [comment]
I use picom and no issues. Maybe it's i3? I use awesomeWM.

**Comment by deepjyoti30** [comment]
@reesericci It is possible. However I have just faced it once or twice randomly and it is never consistent.

**Comment by reesericci** [comment]
can you try FF @mkrasnitski

**Comment by reesericci** [comment]
@deepjyoti30 it seems the user is not replying and this issue should be closed due to being stale.
